// ─────────────────────────────────────────────────────────────
// Argus Export Utilities
// A) exportBrief — PDF-style HTML report
// B) copyShareLink — shareable URL with state encoded as params
// C) downloadCSV — table data as CSV file
// ─────────────────────────────────────────────────────────────

// A) Generate a printable HTML report
export function exportBrief({ title, vertical, market, brand, aiSummary, signals, metrics, date }) {
  const dateStr = date || new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Argus Intelligence Brief — ${title}</title>
  <style>
    *{box-sizing:border-box;margin:0;padding:0}
    body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#0C0F14;color:#E8EDF2;padding:40px;max-width:900px;margin:0 auto}
    .header{border-bottom:2px solid #C9A84C;padding-bottom:24px;margin-bottom:32px}
    .logo{font-size:28px;font-weight:800;letter-spacing:-1px;color:#C9A84C}
    .subtitle{font-size:13px;color:#8A9BB0;margin-top:6px;letter-spacing:0.5px}
    .meta{display:flex;gap:24px;margin-top:16px}
    .meta-item{font-size:12px;color:#8A9BB0}.meta-item strong{color:#E8EDF2}
    .section{margin-bottom:32px}
    .section-title{font-size:11px;font-weight:700;letter-spacing:1.5px;color:#C9A84C;text-transform:uppercase;margin-bottom:16px;padding-bottom:8px;border-bottom:1px solid #1E2A38}
    .summary-box{background:#131920;border:1px solid #1E2A38;border-radius:8px;padding:20px;font-size:15px;line-height:1.7;color:#E8EDF2}
    .signals{display:grid;grid-template-columns:1fr 1fr;gap:12px}
    .signal-card{background:#131920;border:1px solid #1E2A38;border-left:3px solid #C9A84C;border-radius:6px;padding:14px;font-size:13px;line-height:1.5;color:#E8EDF2}
    .metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}
    .metric-card{background:#131920;border:1px solid #1E2A38;border-radius:6px;padding:14px;text-align:center}
    .metric-value{font-size:24px;font-weight:800;color:#C9A84C}
    .metric-label{font-size:11px;color:#8A9BB0;margin-top:4px}
    .footer{margin-top:48px;padding-top:16px;border-top:1px solid #1E2A38;font-size:11px;color:#8A9BB0;display:flex;justify-content:space-between}
    @media print{body{background:#fff;color:#000}.logo{color:#C9A84C}.summary-box,.signal-card,.metric-card{background:#f8f8f8;border-color:#ddd}}
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">◉ ARGUS INTELLIGENCE</div>
    <div class="subtitle">MARKET INTELLIGENCE BRIEF</div>
    <div class="meta">
      <div class="meta-item"><strong>Report:</strong> ${title}</div>
      ${vertical ? `<div class="meta-item"><strong>Vertical:</strong> ${vertical}</div>` : ""}
      ${market ? `<div class="meta-item"><strong>Market:</strong> ${market}</div>` : ""}
      ${brand ? `<div class="meta-item"><strong>Focus:</strong> ${brand}</div>` : ""}
      <div class="meta-item"><strong>Date:</strong> ${dateStr}</div>
    </div>
  </div>

  ${aiSummary ? `
  <div class="section">
    <div class="section-title">AI Intelligence Summary</div>
    <div class="summary-box">${aiSummary}</div>
  </div>` : ""}

  ${signals?.length ? `
  <div class="section">
    <div class="section-title">Key Signals</div>
    <div class="signals">
      ${signals.map(s => `<div class="signal-card">${s}</div>`).join("")}
    </div>
  </div>` : ""}

  ${metrics?.length ? `
  <div class="section">
    <div class="section-title">Key Metrics</div>
    <div class="metrics">
      ${metrics.map(m => `
        <div class="metric-card">
          <div class="metric-value">${m.value}</div>
          <div class="metric-label">${m.label}</div>
        </div>`).join("")}
    </div>
  </div>` : ""}

  <div class="footer">
    <span>Generated by Argus Intelligence Platform</span>
    <span>${dateStr}</span>
  </div>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (win) {
    win.document.write(html);
    win.document.close();
  }
}

// B) Generate shareable URL with state as query params
export function copyShareLink(params) {
  const url = new URL(window.location.href);
  Object.entries(params).forEach(([k, v]) => {
    if (v !== null && v !== undefined && v !== "") {
      url.searchParams.set(k, v);
    }
  });
  const shareUrl = url.toString();
  navigator.clipboard.writeText(shareUrl).catch(() => {
    // Fallback: prompt user
    window.prompt("Copy this link:", shareUrl);
  });
  return shareUrl;
}

// C) Download table data as CSV
export function downloadCSV(data, filename = "argus-export.csv") {
  if (!data || !data.length) return;

  const headers = Object.keys(data[0]);
  const rows = data.map(row =>
    headers.map(h => {
      const val = row[h] == null ? "" : String(row[h]);
      return val.includes(",") || val.includes('"') || val.includes("\n")
        ? `"${val.replace(/"/g, '""')}"`
        : val;
    }).join(",")
  );

  const csv = [headers.join(","), ...rows].join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = filename;
  link.click();
  URL.revokeObjectURL(link.href);
}
